version: "3.7"

services:
  backend:
    container_name: backend-app
    restart: always
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/event_data:/event_data
    environment:
      - PORT=8080
    command: local

  client:
    container_name: next-app
    build:
      context: ./frontend
      args:
        - API=http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
